export const RU_DICTIONARY = {
  reviewForm: {
    shareYourExperience: "Поделитесь своим опытом",
    loginToLeaveReview: "Войдите, чтобы оставить отзыв",
    loginToReview: "Войти",
    editYourReview: "Редактировать отзыв",
    writeAReview: "Написать отзыв",
    reviewingAs: "Отзыв от",
    yourRating: "Ваша оценка",
    title: "Заголовок",
    optional: "(необязательно)",
    summarizeExperience: "Опишите ваш опыт...",
    yourReview: "Ваш отзыв",
    tellUsAboutProduct: "Расскажите нам о продукте...",
    moreCharactersNeeded: "осталось символов",
    characters: "символов",
    submitting: "Отправка...",
    updateReview: "Обновить отзыв",
    submitReview: "Отправить отзыв",
  },

  common: {
    cart: "Корзина",
    checkout: "Оформить заказ",
    search: "Поиск",
    menu: "Меню",
    close: "Закрыть",
    loading: "Загрузка...",
    error: "Произошла ошибка. Пожалуйста, попробуйте еще раз.",
    success: "Успешно!",
    yes: "Да",
    no: "Нет",
    allProducts: "Все товары",
    categories: "Категории",
  },
  footer: {
    becomePartner: "Стать партнером",
    becomePartnerSub: "Начните продавать с Vedashi и охватите тысячи покупателей.",
    registerNow: "Регистрация",
    bulkOrders: "Оптовые заказы",
    bulkOrdersSub: "Запасайтесь продукцией Vedashi по специальным ценам.",
    inquireNow: "Узнать",
    enterEmail: "Введите эл. почту",
    subscribe: "Подписаться",
    followUs: "Мы в соцсетях",
    natural: "100% натурально",
    naturalSub: "Сертифицированная аюрведа",
    freeShipping: "Бесплатная доставка",
    freeShippingSub: "Бесплатная доставка по всему миру",
    authentic: "Аутентичность",
    authenticSub: "Проверенные продавцы",
    securePay: "Безопасная оплата",
    securePaySub: "100% защита",
    madeWith: "Сделано с ♥ в Индии | Вдохновлено Аюрведой, подтверждено наукой.",
    copyright: "© 2026 Vedashi Herbals. Все права защищены.",
    companyDesc: "Забота о вашем пути к целостному здоровью через древнюю мудрость Аюрведы.",
    explore: "Каталог",
    ourStory: "Наша история",
    blogs: "Блог",
    allProducts: "Все товары",
    contactUs: "Связаться с нами",
    support: "Поддержка",
    helpCenter: "Центр помощи",
    shippingPolicy: "Политика доставки",
    returnPolicy: "Политика возврата",
    termsOfService: "Условия обслуживания",
    privacyPolicyFooter: "Политика конфиденциальности",
    newsletter: "Рассылка",
    newsletterDesc: "Получите скидку 10% + еженедельные секреты Аюрведы",
    validEmail: "Пожалуйста, введите действительный email.",
    subscribeSuccess: "Вы успешно подписались!",
    subscribeFailed: "Не удалось подписаться.",
    commError: "Ошибка связи. Пожалуйста, попробуйте позже.",
    becomePartnerAlt: "Стать партнером",
    bulkOrdersAlt: "Оптовые заказы",
    promotionalBannerAlt: "Рекламный баннер",
  },
  nav: {
    home: "Главная",
    products: "Каталог",
    about: "О нас",
    contact: "Контакты",
    blog: "Блог",
    trackOrders: "Отследить заказ",
    hotline: "Горячая линия",
    signInToViewWishlist: "Пожалуйста, войдите в систему, чтобы просмотреть ваш список желаний",
    wishlist: "Избранное",
    cart: "Корзина",
    account: "Аккаунт",
    loginRegister: "Войти / Регистрация",
    openMenu: "Открыть меню",
    closeMenu: "Закрыть меню",
    settings: "Настройки",
    orders: "Заказы",
    logout: "Выход",
    welcomeToVedashi: "Добро пожаловать в Vedashi",
    signInDesc: "Войдите, чтобы отслеживать заказы, сохранять товары и многое другое.",
    signIn: "Войти",
    createAccount: "Создать аккаунт",
    categories: "Категории",
    featuredCollection: "Избранная коллекция",
    exploreCategory: "Откройте для себя",
    discoverDesc: "Откройте для себя наши этично полученные, премиальные аюрведические средства, созданные с традиционной мудростью.",
    shopAll: "Смотреть все",
    profile: "Профиль",
    notificationsTitle: "Уведомления",
    markAllRead: "Прочитать все",
    loadingAlerts: "Загрузка уведомлений...",
    noNotifications: "Пока нет уведомлений",
    weWillNotify: "Мы сообщим вам, когда что-то произойдет.",
    unread: "Непрочитано",
    delete: "Удалить",
    viewAllNotifications: "Все уведомления",
  },
  home: {
    categoriesSubtitle: "Исследуйте нашу коллекцию традиционной мудрости для современной жизни",
    bestSellers: "Бестселлеры",
    bestSellersSubtitle: "Наши самые любимые средства для естественного оздоровления, выбранные вами.",
    newArrivals: "Новинки",
    newArrivalsSubtitle: "Последние дополнения к нашей аюрведической коллекции.",
    faceWash: "Средства для умывания",
    faceWashSubtitle: "Бережное очищение для свежей и сияющей кожи каждый день.",
    shopFaceWash: "Смотреть все средства",
    hairOils: "Масла для волос",
    hairOilsSubtitle: "Питательные масла для сильных, блестящих и здоровых волос.",
    shopHairOils: "Смотреть все масла",
    brandsTitle: "Популярные бренды",
    needHelpTitle: "Нужна помощь в выборе? Начните здесь!",
    shopNow: "В каталог",
    viewAll: "Смотреть все",
    exploreAllProducts: "Смотреть все товары",
    srOnlyTitle: "Vedashi — Премиальные товары для здоровья и красоты",
    exploreAll: "Смотреть все",
  },
  search: {
    pages: "Страницы",
    products: "Товары",
    searching: "Поиск...",
    go: "Найти",
    noResults: "Ничего не найдено по запросу",
    viewAllResults: "Все результаты по запросу",
    pageTitles: {
      home: "Главная",
      allProducts: "Все товары",
      categories: "Категории",
      aboutUs: "О нас",
      contactSupport: "Связаться с поддержкой",
    },
  },
  secondaryNav: {
    brandsAZ: "Бренды А-Я",
    allBrandsAZ: "Все бренды А-Я",
    exploreAll: "Смотреть все",
  },
  plp: {
    filters: "Фильтры",
    category: "Категория",
    allCategories: "Все категории",
    allSubcategories: "Все подкатегории",
    allTypes: "Все типы",
    brand: "Бренд",
    priceRange: "Диапазон цен",
    country: "Страна",
    allCountries: "Все страны",
    rating: "Рейтинг",
    discount: "Скидка",
    form: "Форма",
    specialities: "Специализации",
    availability: "Наличие",
    showing: "Показано",
    of: "из",
    loadingMore: "Загрузка товаров…",
    allCaughtUp: "Все просмотрено",
    noProductsFound: "Товары не найдены",
    tryAdjustingFilters: "Попробуйте изменить фильтры или условия поиска",
    sortBy: "Сортировка",
    noMatchesFound: "Совпадений не найдено",
    searchPlaceholder: "Поиск товаров, брендов...",
    applyFilters: "Применить фильтры",
    clearAll: "Очистить все",
    showingAll: "Показаны все",
    products: "товаров",
    for: "для",
    andAbove: "и выше",
    cancel: "Отмена",
    showLess: "свернуть",
    more: "еще",
    noCountriesFound: "Страны не найдены",
    gridView: "Плитка",
    listView: "Список",
    seo: {
      buyOnline: "Купить {category} онлайн | Аюрведическое здоровье",
      allProductsTitle: "Все товары | Премиальная аюрведическая коллекция",
      categoryDesc: "Купите нашу премиальную коллекцию: {category}. Откройте для себя аутентичные аюрведические продукты, клинически протестированные и натуральные.",
      allProductsDesc: "Купите нашу полную коллекцию премиальных аюрведических оздоровительных продуктов, травяных добавок, натуральной косметики и традиционных индийских специй."
    },
    sort: {
      featured: "Популярные",
      priceLowHigh: "Цена: по возрастанию",
      priceHighLow: "Цена: по убыванию",
      newest: "Сначала новые",
      bestSelling: "Хиты продаж",
      highestRated: "Высокий рейтинг",
      highestDiscount: "Максимальная скидка",
      nameAZ: "Название: А-Я",
      nameZA: "Название: Я-А"
    }
  },
  product: {
    add: "В корзину",
    options: "варианта",
    off: "СКИДКА",
    mrp: "РРЦ",
    addToCart: "В корзину",
    buyNow: "Купить сейчас",
    outOfStock: "Нет в наличии",
    description: "Описание",
    ingredients: "Состав",
    howToUse: "Применение",
    reviews: "Отзывы",
    price: "Цена",
    quantity: "Количество",
    scrollLeft: "Прокрутить влево",
    scrollRight: "Прокрутить вправо",
    noOptionsAvailable: "Нет доступных вариантов.",
    inCart: "В КОРЗИНЕ",
    qty: "КОЛ-ВО",
    unavailable: "Недоступно",
    addToWishlist: "В избранное",
    removeFromWishlist: "Удалить из избранного",
    share: "Поделиться",
  },
  productPage: {
    bestseller: "Бестселлер",
    newArrival: "Новинка",
    noReviewsYet: "Пока нет отзывов",
    boughtThisMonth: "куплено в этом месяце",
    review: "отзыв",
    reviews: "отзывов",
    wow: "ВАУ!",
    limitedTimeOffer: "Ограниченное предложение",
    inclusiveOfTaxes: "Включая все налоги",
    extra10Off: "Дополнительная скидка 10%",
    onlyForNewUsers: "Только для новых пользователей.",
    codeNewUser: "Код: NEWUSER",
    guaranteedDelivery: "Гарантированная доставка в течение",
    daysOfOrdering: "дней после заказа.",
    weight: "Вес:",
    strength: "Крепость",
    volume: "Объем",
    count: "Количество",
    flavour: "Вкус",
    packOf: "В упаковке",
    comingSoon: "Скоро в продаже",
    availabilityEnded: "Продажи завершены",
    notifyMeWhenBackInStock: "Уведомить о появлении",
    enterEmailAddress: "Введите ваш email",
    notifyMe: "Уведомить меня",
    maximumStockReached: "Достигнут максимум на складе",
    dermatologicallyTested: "Одобрено дерматологами",
    safeForAllTypes: "Для всех типов",
    crueltyFree: "Без жестокости",
    natural100: "100% Натурально",
    productDescription: "Описание товара",
    readLess: "Свернуть ▲",
    readMore: "Развернуть ▼",
    buyNow: "Купить сейчас",
    size: "Размер",
    features: "Особенности:",
    brand: "Бренд",
    category: "Категория",
    form: "Форма",
    countryOfOrigin: "Страна",
    unitOfMeasure: "Единица",
    material: "Материал",
    color: "Цвет",
    grade: "Класс",
    shelfLife: "Срок годности",
    dimensions: "Размеры",
    sku: "Артикул",
    months: "месяцев",
    communityExperiences: "Отзывы сообщества",
    storiesOfRestoration: "Истории восстановления и баланса от нашего коллектива.",
    mostRecent: "Сначала новые",
    mostHelpful: "Самые полезные",
    highestRated: "Высокий рейтинг",
    lowestRated: "Низкий рейтинг",
    beTheFirstToShare: "Пока нет отзывов. Поделитесь своим мнением первыми!",
    basedOn: "На основе",
    previewOptions: "Смотреть варианты",
    addToBag: "В корзину",
    imageGallery: "Галерея изображений",
    zoomedView: "Увеличенный вид:",
    browserNoVideo: "Ваш браузер не поддерживает видео.",
    video: "Видео",
    image: "Изображение",
    viewCart: "В корзину",
    addedToCart: "Добавлено в корзину",
    removedFromCart: "Удалено из корзины",
    shareFailed: "Не удалось поделиться",
    shareSuccess: "Ссылка скопирована",
    similarProducts: "Похожие товары",
    recentlyViewed: "Недавно просмотренные"
  },
  checkout: {
    title: "Оформление заказа",
    shipping: "Доставка",
    payment: "Оплата",
    orderSummary: "Ваш заказ",
    placeOrder: "Подтвердить заказ",
    subtotal: "Сумма",
    shippingCost: "Доставка",
    total: "Итого",
  },
  auth: {
    createAccountTitle: "СОЗДАТЬ АККАУНТ",
    welcomeBack: "С ВОЗВРАЩЕНИЕМ!",
    joinFamily: "Присоединяйтесь к семье Vedashi",
    signInToAccount: "Войдите в свой аккаунт",
    fullName: "Полное имя",
    fullNamePlaceholder: "Ваше полное имя",
    emailAddress: "Эл. почта",
    emailPlaceholder: "ваш@email.com",
    password: "Пароль",
    passwordPlaceholder: "••••••••",
    capsLockOn: "Caps Lock Включен",
    rememberMe: "Запомнить меня",
    forgotPassword: "Забыли пароль?",
    confirmPassword: "Подтвердите пароль",
    iAgreeToThe: "Я согласен с",
    termsOfService: "Условиями обслуживания",
    and: "и",
    privacyPolicy: "Политикой конфиденциальности",
    dontHaveAccount: "Нет аккаунта?",
    createAccount: "Создать аккаунт",
    continueAsGuest: "Продолжить как гость",
    sessionExpired: "Сессия истекла",
    sessionExpiredSub: "Срок действия вашей сессии истек из-за неактивности. Пожалуйста, войдите снова.",
    back: "Назад",
    alreadyHaveAccount: "Уже есть аккаунт?",
    loginToAccount: "Войти в аккаунт",
    loginWithPhone: "Войти по телефону",
    pleaseWait: "Пожалуйста, подождите...",
    createAccountButton: "Создать аккаунт →",
    loginButton: "Войти →",
    orContinueWith: "ИЛИ ПРОДОЛЖИТЬ ЧЕРЕЗ",
    continueWithGoogle: "Продолжить с Google",
    continueWithPhone: "Продолжить по телефону",
    signIn: "Войти",
    verifying: "Проверка...",
    verifyAndSignIn: "Проверить и войти →",
    resendOtpIn: "Повторить через",
    resendOtp: "Отправить код еще раз",
    changePhoneNumber: "Изменить номер телефона",
    phonePlaceholder: "Введите номер телефона (10 цифр)",
    sending: "Отправка...",
    sendOtp: "Отправить код",
    yourName: "Ваше имя",
    enterYourName: "Введите ваше имя",
    weWillCreateAccount: "Мы создадим аккаунт для вас",
    enterOtp: "Введите код",
    securingSession: "Защита сессии",
    preparingAccount: "Пожалуйста, подождите, мы подготавливаем ваш аккаунт...",
    enterYourCode: "Введите код",
    signInWithPhoneTitle: "Войти по телефону",
    codeSentTo: "Код отправлен на",
    weWillSendCode: "Мы отправим код подтверждения по SMS",
    phoneNumber: "Номер телефона",
    forgotPasswordTitle: "Забыли пароль",
    checkEmailResetLink: "Проверьте почту для сброса",
    enterEmailResetLink: "Введите почту, и мы отправим ссылку для сброса пароля.",
    weSentEmailTo: "Мы отправили письмо на",
    withResetLink: "со ссылкой для сброса пароля. Доставка может занять несколько минут.",
    returnToLogin: "Вернуться ко входу",
    sendResetLink: "Отправить ссылку для сброса"
  },
  toast: {
    invalidPhone: "Пожалуйста, введите действительный номер телефона",
    otpSent: "OTP-код отправлен на ваш телефон по SMS!",
    failedToSendOtp: "Не удалось отправить OTP-код",
    networkError: "Ошибка сети. Пожалуйста, попробуйте еще раз.",
    enterOtp: "Пожалуйста, введите OTP-код",
    welcomeBack: "С возвращением!",
    invalidOtp: "Неверный OTP-код. Пожалуйста, попробуйте еще раз.",
    agreeToTerms: "Вы должны согласиться с Условиями обслуживания и Политикой конфиденциальности.",
    completeCaptcha: "Пожалуйста, пройдите проверку CAPTCHA.",
    passwordsDoNotMatch: "Пароли не совпадают",
    verifyEmail: "Пожалуйста, подтвердите ваш email для завершения регистрации.",
    somethingWentWrong: "Что-то пошло не так",
    welcomeAdmin: "Добро пожаловать, Админ! Перенаправление в панель управления...",
    tooManyAttempts: "Слишком много неудачных попыток. Пожалуйста, попробуйте еще раз через",
    minutes: "минут(у)",
    completeCaptchaToContinue: "Пожалуйста, пройдите проверку CAPTCHA, чтобы продолжить.",
    loginFailed: "Ошибка входа. Пожалуйста, проверьте ваши данные.",
    serverError: "Ошибка сервера. Пожалуйста, попробуйте еще раз.",
    enterEmailAddress: "Пожалуйста, введите ваш email"
  },
  cart: {
    bag: "КОРЗИНА",
    shipping: "ДОСТАВКА",
    payment: "ОПЛАТА",
    review: "ПРОВЕРКА",
    yourHealingBundleIsEmpty: "Ваша корзина пуста",
    exploreCollection: "Изучите нашу священную коллекцию и добавьте аутентичные аюрведические продукты в свой путь к здоровью",
    exploreSacredShop: "В каталог",
    continueShopping: "Продолжить покупки",
    yourActiveCartIsEmpty: "Ваша активная корзина пуста.",
    browseProducts: "Смотреть товары",
    savedForLater: "Отложенные товары",
    product: "Товар",
    movedToCart: "Перемещено в корзину",
    moveToBag: "В корзину",
    remove: "Удалить",
    removeItem: "Удалить товар",
    areYouSureRemove: "Вы уверены, что хотите удалить этот товар?",
    areYouSureRemoveFromRitual: "Вы уверены, что хотите удалить этот товар из вашей корзины?",
    cancel: "Отмена",
    removedItem: "Товар удален",
    inventoryUpdate: "Обновление наличия",
    someItemsOutOfStock: "Некоторые товары в вашей корзине закончились. Они не будут включены в ваш заказ и будут отложены для последующей покупки.",
    stockLimited: "Ограниченный запас",
    exceedAvailableStock: "Количество одного или нескольких товаров превышает доступный запас. Пожалуйста, измените количество, чтобы продолжить.",
    outOfStock: "Нет в наличии",
    only: "Только",
    leftInStock: "осталось в наличии",
    maximumStockReached: "Достигнут максимум",
    saveForLater: "Отложить",
    orderNotes: "Примечания к заказу",
    optional: "(необязательно)",
    addSpecificAllergies: "Добавьте информацию о специфических аллергиях, предпочтениях или инструкциях по доставке для наших специалистов.",
    typeNotesHere: "Введите ваши примечания здесь...",
    promoOffering: "Промокод",
    haveSacredPromo: "У вас есть промокод? Введите его ниже.",
    couponRemoved: "Промокод удален",
    enterCode: "Введите код",
    couponApplied: "Промокод применен!",
    apply: "Применить",
    investmentSummary: "Ваш заказ",
    item: "Товар",
    items: "Товара",
    preparingPath: "Готовим ваш путь к исцелению",
    noInStockItems: "В корзине нет товаров в наличии",
    qty: "Кол-во:",
    totalMrp: "Цена без скидки",
    discountOnMrp: "Скидка",
    couponDiscount: "Скидка по промокоду",
    platformFee: "Комиссия платформы",
    free: "БЕСПЛАТНО",
    shippingFee: "Стоимость доставки",
    totalSavings: "Вы экономите:",
    totalAmount: "Итого к оплате",
    pleaseSignInToProceed: "Пожалуйста, войдите, чтобы перейти к оформлению",
    failedToSaveOOS: "Не удалось отложить товары:",
    confirmAndCompleteRitual: "Перейти к оплате",
    signInToCheckout: "Войти для оформления",
    secureTransaction: "Безопасная транзакция",
    fastProcessing: "Быстрая обработка",
    needGuidance: "Нужна помощь?",
    vedicAdvisorsAvailable: "Наши ведические консультанты готовы помочь вам с вашей транзакцией.",
    contactSupport: "Служба поддержки",
  },
  checkoutFlow: {
    checkoutCompleted: "Оформление завершено",
    orderId: "Номер заказа:",
    cashOnDelivery: "Оплата при получении",
    paymentConfirmed: "Оплата подтверждена",
    sacredHerbsPrepared: "Ваши священные травы и аутентичные формулы готовятся с заботой. Мы сообщим вам график доставки.",
    continueExploring: "Продолжить покупки",
    trackYourJourney: "Отследить заказ",
    backToPreviousStep: "Вернуться на предыдущий шаг",
    backToBag: "Вернуться в корзину",
    shippingSanctuary: "Адрес доставки",
    deliveryAddress: "Адрес доставки",
    savedAddress: "Сохраненный адрес",
    default: "По умолчанию",
    editAddress: "Изменить адрес",
    countryStar: "Страна *",
    receiversName: "Имя получателя *",
    namePlaceholder: "Имя",
    phoneNumberStar: "Номер телефона *",
    phonePlaceholder: "например, 9876543210",
    pathLine1: "Адрес Строка 1 (Улица, Район) *",
    streetAddress: "Название улицы",
    pathLine2: "Адрес Строка 2 (Необязательно)",
    apartmentSuite: "Квартира, дом и т.д.",
    labelHome: "Название (например, Дом, Работа)",
    homeWorkTemple: "Дом / Работа",
    cancel: "Отмена",
    saveChanges: "Сохранить изменения",
    useDifferentAddress: "Использовать другой адрес",
    searchCountry: "Поиск страны...",
    searchPlaceholder: "Поиск...",
    continueToPayment: "Перейти к оплате",
    paymentMethodology: "Способ оплаты",
    secureCheckout: "БЕЗОПАСНАЯ ОПЛАТА",
    selectPaymentOption: "Выберите способ оплаты для вашего заказа:",
    onlinePayment: "Онлайн-оплата (CloudPayments)",
    mirVisaMastercard: "МИР, Visa, MasterCard, Maestro",
    billingAddress: "Адрес для выставления счета",
    sameAsShipping: "Совпадает с адресом доставки",
    useDifferentBilling: "Использовать другой адрес",
    addressLine1: "Адрес Строка 1 *",
    reviewOrder: "Проверить заказ",
    finalReview: "Финальная проверка",
    shippingTo: "Доставка на имя",
    edit: "Изменить",
    paymentMethod: "Способ оплаты",
    unknownPaymentMethod: "Неизвестный способ оплаты",
    processingRitual: "Обработка заказа...",
    placeFinalOrder: "Оформить заказ —",
    byPlacingOrderYouAgree: "Размещая заказ, вы соглашаетесь с",
    termsOfService: "Условиями обслуживания",
    and: "и",
    privacyPolicy: "Политикой конфиденциальности Vedashi",
    ritualInvestment: "Ваш заказ",
    item: "Товар",
    qty: "Кол-во:",
    off: "% СКИДКА",
    totalMrp: "Цена без скидки",
    discountOnMrp: "Скидка",
    couponDiscount: "Скидка по промокоду",
    loyaltyPoints: "Бонусные баллы",
    platformFee: "Комиссия платформы",
    free: "БЕСПЛАТНО",
    shippingFee: "Стоимость доставки",
    add: "Добавьте",
    moreForFreeShipping: "еще для бесплатной доставки",
    youAreSaving: "Вы экономите",
    onThisOrder: "на этом заказе",
    totalAmount: "Итого к оплате",
    promoCode: "Промокод",
    enterCode: "Введите код",
    couponApplied: "Промокод применен!",
    apply: "Применить",
    available: "доступно",
    max: "Макс.",
    applied: "применено",
    allTransactionsAreEncrypted: "Все транзакции зашифрованы и подлинны.",
    deleteAddressQ: "Удалить адрес?",
    areYouSureDeleteAddress: "Вы уверены, что хотите удалить этот адрес? Это действие нельзя отменить.",
    delete: "Удалить",
  },
  notificationsTab: {
    title: "Ваши уведомления",
    subtitle: "Оповещения о безопасности и обновлениях",
    markAllAsRead: "Отметить все как прочитанные",
    innerPeace: "Внутреннее спокойствие",
    noNotifications: "У вас пока нет новых уведомлений. Сохраняйте осознанность и наслаждайтесь своим путем к здоровью.",
    viewDetails: "ПОДРОБНЕЕ",
    markAsRead: "ПРОЧИТАТЬ",
    seen: "Просмотрено",
    showing: "Показано",
    of: "из",
    notifications: "уведомлений",
    previous: "Назад",
    next: "Вперед",
    toast: {
      allMarkedRead: "Все отмечены как прочитанные",
      failedUpdate: "Не удалось обновить",
      removed: "Уведомление удалено",
      failedDelete: "Не удалось удалить"
    }
  },
  ordersTab: {
    // Header & Badge
    ordersList: "Список заказов",
    total: "Всего",
    of: "из",
    // Search
    searchPlaceholder: "Поиск по номеру заказа или названию товара...",
    // Status Filters
    all: "Все",
    pending: "В ожидании",
    shipped: "Отправлен",
    delivered: "Доставлен",
    cancelled: "Отменен",
    // Sort
    sort: "СОРТИРОВКА:",
    newestFirst: "Сначала новые",
    oldestFirst: "Сначала старые",
    amountHighLow: "Сумма: по убыванию",
    amountLowHigh: "Сумма: по возрастанию",
    // Empty States
    noOrdersYet: "Заказов пока нет",
    tryAdjustingFilters: "Попробуйте изменить фильтры.",
    noOrdersPlaced: "Вы еще не сделали ни одного заказа.",
    // Order Card Labels
    orderId: "НОМЕР ЗАКАЗА",
    datePlaced: "ДАТА ЗАКАЗА",
    totalAmount: "СУММА ЗАКАЗА",
    // Order Card Item Info
    andMore: "и ещё",
    moreItems: "товар(ов)",
    soldByVedashi: "Продавец: Vedashi",
    // Order Card Actions
    viewDetails: "Подробнее",
    reorder: "Повторить заказ",
    reordering: "Повторяем заказ...",
    // Pagination
    showing: "Показано",
    orders: "заказов",
    // Details Panel
    orderDetails: "Детали заказа",
    orderIdLabel: "Номер заказа:",
    trackShipment: "Отслеживание",
    deliveredOn: "Доставлен",
    shippedOn: "Отправлен",
    confirmedOn: "Подтвержден",
    orderedOn: "Заказан",
    trackOrder: "Отследить заказ",
    // Items & Payment
    itemsSummary: "Состав заказа",
    qty: "Кол-во:",
    shippingAddress: "Адрес доставки",
    paymentInfo: "Оплата",
    subtotal: "Подытог",
    ecoShipping: "Эко-доставка",
    free: "БЕСПЛАТНО",
    totalLabel: "Итого",
    // Detail Actions
    invoice: "Счёт",
    downloading: "Загрузка...",
    viewTicket: "Посмотреть запрос",
    support: "Поддержка",
    cancelOrder: "Отменить заказ",
    inquiryCorrespondence: "Переписка по запросу",
    accessAllMessages: "Все сообщения",
    buyAgain: "Купить эти товары снова",
    addingToCart: "Добавляем в корзину...",
    // Empty Detail State
    selectAnOrder: "Выберите заказ",
    selectAnOrderDesc: "Выберите заказ из списка, чтобы посмотреть отслеживание, товары и оплату.",
    // Cancel Modal
    cancelOrderTitle: "Отмена заказа",
    cancelOrderDesc: "Пожалуйста, сообщите нам причину отмены заказа.",
    cancelReasonPlaceholder: "Причина отмены...",
    keepOrder: "Оставить заказ",
    cancelling: "Отменяем...",
    // Review Modal
    verifiedPurchaseReview: "Отзыв о подтвержденной покупке",
    reviewing: "Отзыв на:",
    verifiedBadgeNote: "Этот отзыв получит значок «Подтвержденная покупка», так как ваш заказ был доставлен.",
    // Track Order Modal
    trackLabels: {
      pending: "Семя посеяно",
      confirmed: "Росток растёт",
      shipped: "Листья распускаются",
      delivered: "Цветок распустился",
      cancelled: "Растение увяло",
    },
    fetchingLogistics: "Загрузка данных о доставке...",
    currentStatus: "Текущий статус",
    processing: "В обработке",
    liveMap: "Карта в реальном времени",
    orderBeingPrepared: "Ваш заказ готовится.",
    seedSownCheckBack: "Семя посеяно. Вернитесь позже для обновлений.",
    close: "Закрыть",
    // Toasts
    toast: {
      orderCancelledSuccess: "Заказ успешно отменён.",
      failedToCancel: "Не удалось отменить заказ.",
      cancelError: "Произошла ошибка при отмене.",
      couldNotFetchOrder: "Не удалось получить данные заказа для повтора.",
      noItemsFound: "Товары в этом заказе не найдены.",
      checkingCartStock: "Проверяем корзину и наличие...",
      allItemsInCart: "Все товары уже в корзине в максимальном количестве.",
      allOutOfStock: "Все товары закончились.",
      addedItemsLimited: "товар(ов). Некоторые ограничены из-за наличия.",
      addedPrefix: "Добавлено",
      itemsAddedSuccess: "Товары успешно добавлены в корзину!",
      couldNotAddItems: "Не удалось добавить товары.",
      reorderError: "Произошла непредвиденная ошибка при повторе заказа.",
      invoiceDownloaded: "Счёт успешно загружен",
      invoiceFailed: "Не удалось загрузить счёт",
      reviewSubmitted: "Отзыв с значком «Подтвержденная покупка» отправлен!",
    }
  },
  walletTab: {
    // Toasts
    failedToLoad: "Не удалось загрузить данные кошелька.",
    // Empty State / Not Activated
    notActivatedTitle: "Святилище не активировано",
    notActivatedDesc: "Встаньте на путь к здоровью. Ваш журнал ритуалов начнется с первой осознанной покупки.",
    beginJourney: "Начать путешествие",
    // Header
    rewardsTitle: "Ведические ритуальные награды",
    rewardsSubtitle: "Ваш путь к целостному здоровью вознаграждается.",
    // Active Plan Card
    activePlan: "Активный план",
    ritualist: "Ритуалист",
    unlockPotential: "Раскройте свой потенциал. Ваш путь к здоровью только начинается.",
    balance: "Баланс",
    points: "Баллы",
    bronze: "Бронзовый",
    tiers: {
      Bronze: "Бронзовый",
      Silver: "Серебряный",
      Gold: "Золотой",
      Platinum: "Платиновый",
      Diamond: "Бриллиантовый"
    },
    // Lifetime Stats
    gainedPoints: "Накопленные баллы",
    sharedBlessings: "Поделенные благословения",
    // Tier Benefits
    tierBenefits: "Преимущества уровня",
    multiplier: "Множитель:",
    discount: "Скидка:",
    // Transaction History
    ritualJournal: "Журнал ритуалов",
    realTimeHistory: "История в реальном времени",
    emptyJournal: "Пустой журнал",
    emptyJournalDesc: "Ваш путь только начался. Получайте баллы, участвуя в ритуалах и оставляя отзывы.",
    refPrefix: "Заказ: #",
    auraExpires: "Сгорают:",
    postAura: "Остаток:",
    // Transaction Types map
    transactionTypes: {
      earned_purchase: "Начислено за покупку",
      earned_review: "Начислено за отзыв",
      earned_referral: "Начислено за приглашение",
      redeemed_order: "Списано за заказ",
      reversed: "Отменено",
      expired: "Сгорели"
    },
    // Footer
    essenceTitle: "Суть взаимности",
    essenceQuote: "\"В Природе всё отданное возвращается в изобилии. Ваша преданность отражает гармонию наших общих ценностей.\""
  },
  account: {
    coreExperience: "ОСНОВНОЕ",
    overview: "Обзор",
    notifications: "Уведомления",
    orders: "Заказы",
    wishlist: "Избранное",
    myWallet: "Мой кошелек",
    identityAccess: "ЛИЧНЫЕ ДАННЫЕ И ДОСТУП",
    personalProfile: "Личный профиль",
    manageAddresses: "Адреса",
    supportEnquiries: "Поддержка и запросы",
    privacySanctuary: "Конфиденциальность",
    goldStatus: "ЗОЛОТОЙ СТАТУС",
    goldStatusDesc: "Вы находитесь на ранге Золотого ритуалиста.",
    viewBenefits: "СМОТРЕТЬ ПРИВИЛЕГИИ >",
    verifiedMember: "ПРОВЕРЕННЫЙ ПОЛЬЗОВАТЕЛЬ",
    accountOverview: "Обзор аккаунта",
    account: "Аккаунт",
    mySanctuary: "МОЕ ПРОСТРАНСТВО",
    wishlistHeaderLine1: "Ваш личный список",
    wishlistHeaderLine2: "избранных товаров",
    wishlistDesc: "Отобранное пространство для ритуалов, которые вы любите. Следите за вашими органическими средствами и инструментами для здоровья.",
    totalItemsSaved: "ТОВАРОВ СОХРАНЕНО",
    openingSanctuary: "Открываем ваше пространство...",
    wishlistEmpty: "Ваш список избранного пуст",
    saveOrganicRituals: "Сохраняйте ваши любимые органические ритуалы здесь.",
    findMore: "Найти еще",
    exploreCollections: "Исследуйте наши коллекции.",
    browseShop: "В каталог",
    manageFullWishlist: "Управление избранным",
    removeItemTitle: "Удалить товар",
    removeWishlistConfirm: "Вы уверены, что хотите удалить этот товар из вашего пространства?",
    itemRemoved: "Товар удален из избранного",
    failedToRemove: "Не удалось удалить товар",
    remove: "Удалить",
    cancel: "Отмена",
    savedItems: "Сохраненные товары",
    waitlistingItems: "В листе ожидания",
    wishlistPreview: "Предпросмотр",
    sanctuaryEmpty: "Ваше пространство пусто.",
    yourPersonalWellness: "Ваше личное здоровье",
    noMatchesSort: "Нет совпадений для текущей сортировки.",
    previous: "Назад",
    next: "Вперед",
    statusConfirmed: "ПОДТВЕРЖДЕН",
    statusCompleted: "ВЫПОЛНЕН",
    statusShipped: "ОТПРАВЛЕН",
    statusProcessing: "В ОБРАБОТКЕ",
    statusDelivered: "ДОСТАВЛЕН",
    statusCancelled: "ОТМЕНЕН",
    namaste: "Намасте, {name}.",
    welcomeBack: "Добро пожаловать в ваше пространство. Ваше путешествие к здоровью продолжается с той же чистотой и преданностью.",
    trackLatestOrder: "Отследить последний заказ",
    updateHealthProfile: "Обновить профиль",
    recentOrders: "Последние заказы",
    total: "Всего",
    currentlyInTransit: "сейчас в пути",
    loyaltyPoints: "Бонусные баллы",
    pts: "баллов",
    commonActions: "Частые действия",
    viewAllOrders: "Смотреть все заказы",
    checkStatusHistory: "Проверка статуса и истории",
    addEditDeliverySpots: "Добавить или изменить адреса",
    accountSettings: "Настройки аккаунта",
    editProfilePrivacy: "Редактировать профиль и приватность",
    recentOrdersSummary: "Сводка последних заказов",
    latestTransactions: "Ваши последние транзакции",
    seeFullHistory: "Вся история",
    orderId: "Номер заказа",
    date: "Дата",
    status: "Статус",
    amount: "Сумма",
    pending: "В ОЖИДАНИИ",
    noOrderHistory: "История заказов пока недоступна.",
    vedashiWallet: "Кошелек Vedashi",
    availableBalance: "Доступный баланс",
    loyaltySidebar: {
      status: "СТАТУС",
      youPossess: "В настоящее время у вас ранг",
      ritualistRank: "ритуалиста.",
      viewBenefits: "ПОСМОТРЕТЬ ПРЕИМУЩЕСТВА",
      tiers: {
        Bronze: "Бронзовый",
        Silver: "Серебряный",
        Gold: "Золотой",
        Platinum: "Платиновый",
        Diamond: "Бриллиантовый"
      }
    },
},
  addressesTab: {
    header: {
      yourAddresses: "Ваши адреса",
      manageDestinations: "Управляйте адресами для ваших заказов.",
      manageAddresses: "Управление адресами"
    },
    empty: {
      noSavedRituals: "Нет сохраненных адресов",
      defineFirstSpace: "Укажите свой первый адрес доставки, чтобы начать путешествие.",
      addAddress: "Добавить адрес"
    },
    list: {
      primarySpace: "ОСНОВНОЙ АДРЕС",
      setPrimary: "Сделать основным",
      editDetails: "Изменить данные",
      deleteSpace: "Удалить адрес"
    },
    form: {
      addNewAddressCard: "Добавить новый адрес",
      editAddress: "Изменить адрес",
      addNewAddressForm: "Добавить новый адрес",
      country: "Страна",
      receiverName: "Имя получателя",
      namePlaceholder: "Имя",
      phoneNumber: "Номер телефона",
      phoneError: "Должно быть от 7 до 12 цифр",
      pathLine1: "Адрес, строка 1 (Улица, Район)",
      pathLine2: "Адрес, строка 2 (Необязательно)",
      labelTitle: "Название (например, Дом, Офис)",
      labelPlaceholder: "Дом / Работа / Офис",
      setPrincipal: "Сделать основным адресом (по умолчанию)",
      back: "Назад",
      saveChanges: "Сохранить изменения",
      addAddressBtn: "Добавить адрес"
    },
    modal: {
      deleteTitle: "Удалить адрес",
      deleteDesc: "Вы уверены, что хотите навсегда удалить этот адрес? Это действие нельзя будет отменить.",
      deleteBtn: "Удалить",
      cancelBtn: "Отмена"
    },
    toast: {
      fillRequired: "Пожалуйста, заполните все обязательные поля",
      phoneLength: "Номер телефона должен содержать от 7 до 12 цифр",
      addressUpdated: "Адрес обновлен",
      failedUpdate: "Не удалось обновить адрес",
      addressAdded: "Адрес добавлен",
      failedAdd: "Не удалось добавить адрес",
      addressDeleted: "Адрес удален",
      failedDelete: "Не удалось удалить адрес",
      defaultUpdated: "Основной адрес обновлен",
      failedDefault: "Не удалось установить по умолчанию",
      somethingWentWrong: "Что-то пошло не так"
    }
  },
  supportTab: {
    header: {
      viewAndManage: "Просматривайте и управляйте вашими запросами в службу поддержки",
      backToList: "Вернуться к списку",
      historyTitle: "История обращений в поддержку",
      historyDesc: "История ваших прошлых взаимодействий и решений",
      searchEnquiries: "Поиск запросов..."
    },
    empty: {
      recallingHistory: "Восстановление истории...",
      noPastEnquiries: "Нет прошлых обращений",
      pathSmooth: "Ваш путь был гладким! Если вам когда-нибудь понадобится помощь, наша служба поддержки всегда на связи.",
      createNewTicket: "Создать новый запрос",
      awaitingAdmin: "Ожидание ответа администратора",
      supportReceived: "Наша служба поддержки получила ваш запрос и ответит в течение 24-48 часов."
    },
    detail: {
      fallbackInquiry: "Запрос",
      fallbackSubject: "Без темы",
      fallbackPending: "В ожидании",
      supportSpecialist: "Специалист поддержки",
      you: "Вы",
      typeMessage: "Введите ваше сообщение здесь...",
      teamResponds: "Наша команда обычно отвечает в течение 24-48 часов. Спасибо за ваше терпение."
    },
    sidebar: {
      addMoreInfo: "Нужно добавить больше информации?",
      teamHereToHelp: "Наша служба поддержки готова помочь. Вы получите уведомление по электронной почте, как только мы ответим.",
      submitNew: "Отправить новый запрос",
      ticketInsight: "Информация о запросе",
      ticketId: "Номер запроса",
      requestedOn: "Дата запроса",
      priorityRange: "Приоритет",
      standardPriority: "Стандартный",
      category: "Категория",
      fallbackGeneral: "Общая",
      supportPhilosophy: "Философия поддержки",
      philosophyText: "В Vedashi мы относимся к каждому запросу с такой же внимательностью, как и к созданию наших продуктов. Спасибо за ваше терпение.",
      viewHelpCenter: "Открыть Справочный центр"
    },
    list: {
      ticketBadge: "Запрос",
      fallbackEnquiry: "Стандартный запрос",
      messages: "Сообщения"
    },
    toast: {
      sendingMessage: "Отправка сообщения...",
      messageSent: "Сообщение успешно отправлено",
      failedToSend: "Не удалось отправить сообщение",
      networkError: "Ошибка сети"
    }
  },
  profileTab: {
    overview: {
      lifetimeMember: "Пожизненный участник",
      memberSince: "Энтузиаст здорового образа жизни • Участник с",
      fallbackDate: "Сентябрь 2021",
      ritualsDone: "Пройдено ритуалов",
      soulfulReviews: "Душевных отзывов",
      seedPoints: "Семена-баллы"
    },
    form: {
      personalEssence: "Личные данные",
      fullIdentity: "Полное имя",
      soulfulMail: "Электронная почта",
      mobileNumber: "Номер телефона",
      code: "Код",
      dateOfBirth: "Дата рождения",
      currentLocation: "Текущее местоположение",
      noAddressAdded: "Адрес не добавлен",
      locationDerived: "Местоположение определяется вашим основным адресом доставки"
    },
    security: {
      securitySanctuary: "Убежище безопасности",
      protectSanctum: "Защитите свое внутреннее святилище надежным паролем.",
      modifyAccessPassword: "Изменить пароль доступа",
      setAccessPassword: "Установить пароль доступа",
      accountSecured: "Ваш аккаунт защищен",
      notificationHarmony: "Гармония уведомлений",
      tuneAlerts: "Настройте оповещения и оставайтесь в гармонии со своим путем.",
      manageNotifications: "Управление уведомлениями"
    },
    actions: {
      saveAllChanges: "СОХРАНИТЬ ВСЕ ИЗМЕНЕНИЯ",
      discardModifications: "Отменить изменения",
      activePlan: "АКТИВНЫЙ ПЛАН",
      ritualist: "Ритуалист",
      enhanceAura: "Усиливайте свою ауру с каждым ритуалом, чтобы разблокировать экзотические преимущества.",
      manageRewards: "Управление наградами"
    },
    status: {
      accountStatus: "СТАТУС АККАУНТА",
      email: "Почта",
      mobile: "Телефон",
      verified: "Подтвержден",
      verify: "Подтвердить",
      initiateDeletion: "Инициировать удаление аккаунта"
    },
    image: {
      removePhoto: "Удалить фото",
      uploadPhoto: "Загрузить фото"
    },
    modals: {
      emailOtp: {
        verifyEmailChange: "Подтверждение изменения почты",
        secureVerificationCodeSent: "Мы отправили безопасный код подтверждения на",
        enterCodeBelow: ". Пожалуйста, введите код ниже, чтобы подтвердить.",
        secureCodeOtp: "Безопасный код (OTP)",
        enter6DigitCode: "Введите 6-значный код",
        verifyAndSave: "Подтвердить и сохранить",
        resendSecureCode: "Отправить код повторно",
        resendCodeIn: "Отправить повторно через"
      },
      phoneOtp: {
        verifyMobileNumber: "Подтверждение номера мобильного телефона",
        verificationCodeSentEnd: "Мы отправили 6-значный код подтверждения на ваш новый мобильный номер, оканчивающийся на",
        verificationCode: "Код подтверждения",
        verifyAndUpdate: "Подтвердить и обновить",
        resendVerificationSms: "Отправить SMS повторно",
        resendSmsIn: "Отправить SMS повторно через"
      },
      password: {
        modifyPassword: "Изменить пароль",
        setPassword: "Установить пароль",
        currentPassword: "Текущий пароль",
        newPassword: "Новый пароль",
        confirmNewPassword: "Подтвердите новый пароль",
        updatingSanctuary: "Обновление убежища...",
        updateCredentials: "Обновить учетные данные"
      },
      deactivation: {
        confirmDeactivation: "Подтвердить деактивацию",
        enterPasswordConfirm: "Пожалуйста, введите ваш пароль для подтверждения деактивации аккаунта.",
        enterYourPassword: "Введите ваш пароль",
        deactivating: "Деактивация...",
        deactivate: "Деактивировать"
      },
      notification: {
        notificationHarmony: "Гармония уведомлений",
        customiseAlerts: "Настройте свои осознанные оповещения",
        masterPresence: "Овладейте своим периодическим присутствием через осознанные оповещения.",
        done: "ГОТОВО"
      }
    },
    notificationPreferences: {
      channels: {
        email: { label: "Email", desc: "Получать уведомления по электронной почте" },
        sms: { label: "SMS", desc: "Получать уведомления по SMS" },
        whatsapp: { label: "WhatsApp", desc: "Получать уведомления в WhatsApp" },
        push: { label: "Push-уведомления", desc: "Push-уведомления в браузере и приложении" }
      },
      categories: {
        orderUpdates: { label: "Обновления заказов и доставки", desc: "Подтверждение заказа, изменение статуса, доставка" },
        accountSecurity: { label: "Аккаунт и безопасность", desc: "Уведомления о входе, смена пароля" },
        promotions: { label: "Акции и предложения", desc: "Распродажи, скидки, специальные предложения" },
        priceAlerts: { label: "Уведомления о ценах", desc: "Снижение цен на товары из избранного" },
        newsletter: { label: "Новостная рассылка", desc: "Еженедельные подборки и статьи" }
      },
      toasts: {
        loadFailed: "Не удалось загрузить настройки уведомлений",
        updateFailed: "Не удалось обновить настройку",
        updateSuccess: "Настройка успешно обновлена",
        networkError: "Ошибка сети. Пожалуйста, попробуйте еще раз."
      },
      header: {
        title: "Настройки уведомлений",
        desc: "Управляйте тем, как вы хотите получать от нас оповещения и обновления",
        receiveVia: "Получать уведомления через:",
        selectChannels: "Выберите каналы для ваших периодических оповещений"
      },
      badges: {
        active: "Активен",
        unverified: "Не подтвержден",
        soon: "Скоро",
        verificationRequired: "Требуется подтверждение"
      },
      footer: {
        noteLabel: "Примечание:",
        noteText: "Уведомления о безопасности аккаунта (предупреждения о входе, смена пароля) всегда отправляются по электронной почте для вашей безопасности и не могут быть полностью отключены. Для SMS-уведомлений требуется подтвержденный номер телефона в вашем аккаунте."
      }
    },
    toasts: {
      imageSize: "Размер изображения не должен превышать 5МБ",
      photoUpdated: "Фото профиля обновлено!",
      uploadFailed: "Не удалось загрузить изображение",
      uploadRetry: "Сбой загрузки. Пожалуйста, попробуйте еще раз.",
      couldNotRead: "Не удалось прочитать файл",
      photoRemoved: "Фото профиля удалено",
      removeFailed: "Не удалось удалить изображение",
      serverError: "Ошибка сервера",
      discarded: "Изменения отменены",
      phoneDigits: "Номер телефона может содержать только цифры и префикс +.",
      phoneLength: "Номер телефона должен содержать от 7 до 15 цифр.",
      profileUpdated: "Профиль успешно обновлен",
      profileUpdateFailed: "Не удалось обновить профиль",
      generalServerError: "Ошибка сервера. Пожалуйста, попробуйте еще раз.",
      emailCodeSent: "Код подтверждения отправлен на вашу новую почту",
      emailChangeReqFailed: "Не удалось запросить изменение почты",
      phoneCodeSent: "Код подтверждения отправлен на ваш новый номер мобильного телефона",
      phoneCodeReqFailed: "Не удалось отправить код подтверждения на новый номер",
      phoneVerifyReqFailed: "Не удалось запросить подтверждение номера",
      newCodeSent: "Новый код подтверждения отправлен",
      resendFailed: "Не удалось отправить код повторно",
      enterOtp: "Пожалуйста, введите OTP",
      phoneUpdatedAndVerified: "Мобильный номер обновлен и подтвержден!",
      invalidOtp: "Неверный или просроченный OTP",
      emailUpdated: "Почта успешно обновлена",
      profileAllUpdated: "Весь профиль обновлен",
      samePassword: "Новый пароль не может совпадать с текущим паролем",
      passwordMismatch: "Пароли не совпадают",
      passwordLength: "Пароль должен состоять минимум из 8 символов",
      passwordUpdated: "Пароль успешно обновлен",
      passwordUpdateFailed: "Не удалось обновить пароль",
      passwordRequired: "Требуется пароль",
      accountDeactivated: "Аккаунт деактивирован. Вы можете восстановить его в любое время.",
      deactivateFailed: "Не удалось деактивировать аккаунт"
    },
    verifyOtpPage: {
      toasts: {
        codeSent: "Код подтверждения отправлен на ваш телефон по SMS!",
        alreadyVerified: "Номер мобильного телефона уже подтвержден!",
        sendFailed: "Не удалось отправить код подтверждения",
        networkError: "Ошибка сети. Пожалуйста, попробуйте еще раз.",
        verifySuccess: "Мобильный номер успешно подтвержден!",
        invalidCode: "Неверный код подтверждения",
        incompleteCode: "Пожалуйста, введите полный 6-значный код"
      },
      ui: {
        backToAccount: "Назад к аккаунту",
        mobileVerified: "Мобильный подтвержден!",
        verifyMobileNumber: "Подтверждение номера",
        numberHasBeenVerified: "Ваш мобильный номер был подтвержден",
        weSentCodeTo: "Мы отправили 6-значный код на ваш телефон",
        linkedTo: " (привязанный к ",
        redirecting: "Перенаправление в ваш аккаунт...",
        verifying: "Проверка...",
        verifyMobileBtn: "Подтвердить номер",
        didntReceive: "Не получили код?",
        resendIn: "Отправить повторно через",
        sending: "Отправка...",
        resendCode: "Отправить код повторно"
      }
    }
  },
  privacyTab: {
    title: "Конфиденциальность и управление данными",
    subtitle: "Управляйте своими личными данными в соответствии с правилами GDPR.",
    dataSubjectsRights: "Ваши права субъекта данных",
    dataSubjectsRightsDesc: "В соответствии с Общим регламентом по защите данных (GDPR) вы имеете право на доступ, исправление, перенос и удаление вашей личной информации. Используйте инструменты ниже для автоматического осуществления этих прав.",
    readPrivacyPolicy: "Читать нашу политику конфиденциальности",
    dataPortability: "Переносимость данных",
    dataPortabilityDesc: "Загрузите машиночитаемый JSON-файл, содержащий все ваши личные данные, заказы и адреса.",
    exportMyData: "Экспортировать мои данные",
    rightToBeForgotten: "Право на забвение",
    rightToBeForgottenDesc: "Навсегда анонимизировать вашу личную информацию. Это действие приведет к немедленному удалению вашего аккаунта.",
    erasePersonalData: "Удалить личные данные",
    dataRequestLog: "Журнал запросов данных",
    article30Compliance: "Поддерживается в соответствии со статьей 30",
    noPrivacyRequests: "Предыдущих запросов конфиденциальности не найдено.",
    exportSuccess: "Данные успешно экспортированы.",
    exportFailed: "Не удалось экспортировать данные.",
    networkErrorExport: "Ошибка сети при экспорте.",
    erasureWarning: "ВНИМАНИЕ: Это действие необратимо. Ваши личные данные будут полностью анонимизированы, а ваш аккаунт удален. Вы абсолютно уверены?",
    erasureSuccess: "Аккаунт успешно удален.",
    erasureFailed: "Не удалось удалить аккаунт.",
    networkErrorErasure: "Ошибка сети при запросе на удаление.",
  
    requestTypes: {
      ACCESS: "Доступ",
      RECTIFICATION: "Исправление",
      ERASURE: "Удаление",
      RESTRICTION: "Ограничение",
      PORTABILITY: "Переносимость",
      OBJECT: "Возражение"
    },
    requestStatuses: {
      PENDING: "Ожидается",
      COMPLETED: "Завершено",
      REJECTED: "Отклонено",
      PROCESSING: "В обработке"
    }
},
};