export const ROUTES = {
  home: '/',
  katalog: '/katalog',
  katalogPath: (fullPath: string) => `/katalog/${fullPath}`,
  tovar: (slug: string) => `/tovar/${slug}`,
  korzina: '/korzina',
  checkout: '/oformlenie-zakaza',
  account: '/lichnyy-kabinet',
  accountTab: (tab: string) => `/lichnyy-kabinet/${tab}`,
  login: '/vhod',
  search: '/poisk',
  collections: (slug: string) => `/podborki/${slug}`,
  about: '/o-nas',
  contact: '/kontakty',
  helpCenter: '/pomoshch',
  helpCenterFaq: '/pomoshch/chavo',
  helpCenterKnowledgeBase: '/pomoshch/baza-znaniy',
  helpCenterKnowledgeBaseArticle: (slug: string) => `/pomoshch/baza-znaniy/${slug}`,
  helpCenterSupport: '/pomoshch/podderzhka',
  helpCenterSupportTicket: (id: string) => `/pomoshch/podderzhka/${id}`,
  helpCenterCustomerEnquiry: '/pomoshch/zapros-klienta',
  legal: (slug: string) => `/${slug}`,
  forgotPassword: '/zabyly-parol',
  resetPassword: '/sbros-parolya',
  verifyEmail: '/podtverzhdenie-email',
  verifyOtp: '/podtverzhdenie-otp',
  vendorRegistration: '/registratsiya-postavshchika',
  blog: '/blog',
} as const;

export const ACCOUNT_TABS = {
  overview: 'obzor',
  orders: 'zakazy',
  profile: 'profil',
  wishlist: 'izbrannoe',
  wallet: 'koshelyok',
  addresses: 'adresa',
  notifications: 'uvedomleniya',
  settings: 'nastroyki',
  privacy: 'konfidentsialnost',
  support: 'podderzhka',
} as const;
